/* eslint-disable no-unused-vars */
/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'steam-friends adapter settings': {
		en: 'Adapter settings for steam-friends',
		de: 'Adaptereinstellungen für steam-friends',
		ru: 'Настройки адаптера для steam-friends',
		pt: 'Configurações do adaptador para steam-friends',
		nl: 'Adapterinstellingen voor steam-friends',
		fr: "Paramètres d'adaptateur pour steam-friends",
		it: "Impostazioni dell'adattatore per steam-friends",
		es: 'Ajustes del adaptador para steam-friends',
		pl: 'Ustawienia adaptera dla steam-friends',
		'zh-cn': 'steam-friends的适配器设置',
	},
	'var-apikey': {
		en: 'Your API-Key',
		de: 'Ihr API-Schlüssel',
		ru: 'Ваш API-ключ',
		pt: 'Sua chave de API',
		nl: 'Uw API-sleutel',
		fr: 'Votre clé API',
		it: 'La tua chiave API',
		es: 'Su clave API',
		pl: 'Twój klucz API',
		'zh-cn': '您的 API 密钥',
	},
	'var-refresh': {
		en: 'Update interval (in seconds | please use at least 5 seconds)',
		de: 'Aktualisierungsintervall (in Sekunden | bitte mindestens 5 Sekunden verwenden)',
		ru: 'Интервал обновления (в секундах | используйте не менее 5 секунд)',
		pt: 'Intervalo de atualização (em segundos | use pelo menos 5 segundos)',
		nl: 'Update-interval (in seconden | gebruik a.u.b. minimaal 5 seconden)',
		fr: 'Intervalle de mise à jour (en secondes | veuillez utiliser au moins 5 secondes)',
		it: 'Intervallo di aggiornamento (in secondi | si prega di utilizzare almeno 5 secondi)',
		es: 'Intervalo de actualización (en segundos | utilice al menos 5 segundos)',
		pl: 'Interwał aktualizacji (w sekundach | użyj co najmniej 5 sekund)',
		'zh-cn': '更新间隔（以秒为单位 | 请至少使用 5 秒）',
	},
	'var-steamid': {
		en: 'Your Steam-ID',
		de: 'Ihre Steam-ID',
		ru: 'Ваш Steam-ID',
		pt: 'Seu Steam ID',
		nl: 'Je Steam-ID',
		fr: 'Votre identifiant Steam',
		it: 'Il tuo Steam ID',
		es: 'Tu ID de Steam',
		pl: 'Twój identyfikator Steam',
		'zh-cn': '您的 Steam-ID',
	},
	'tab-main': {
		en: 'Main Settings',
		de: 'Haupteinstellungen',
		ru: 'Основные параметры',
		pt: 'Configurações principais',
		nl: 'Belangrijkste instellingen',
		fr: 'Réglages principaux',
		it: 'Impostazioni principali',
		es: 'Ajustes principales',
		pl: 'Ustawienia główne',
		'zh-cn': '主要设置',
	},
	'tab-visibility': {
		en: 'Change visibility',
		de: 'Sichtbarkeit ändern',
		ru: 'Изменить видимость',
		pt: 'Alterar visibilidade',
		nl: 'Zichtbaarheid wijzigen',
		fr: 'Modifier la visibilité',
		it: 'Cambia visibilità',
		es: 'Cambiar visibilidad',
		pl: 'Zmień widoczność',
		'zh-cn': '更改可见性',
	},
	'text-soon': {
		en: 'This feature is coming soon. Please stay patient',
		de: 'Diese Funktion kommt bald. Bitte bleiben Sie geduldig',
		ru: 'Эта функция появится в ближайшее время. Пожалуйста, оставайтесь терпеливыми',
		pt: 'Esta funcionalidade estará disponível em breve. Por favor, seja paciente',
		nl: 'Deze functie komt binnenkort. Blijf alsjeblieft geduldig',
		fr: 'Cette option sera disponible sous peu. Merci de rester patient',
		it: 'Questa funzionalità arriverà presto. Per favore, sii paziente',
		es: 'Esta característica estará disponible en breve. por favor ten paciencia',
		pl: 'Ta funkcja będzie dostępna wkrótce. Prosimy o cierpliwość',
		'zh-cn': '此功能即将推出。请耐心等待',
	},
	'title-general': {
		en: 'General settings',
		de: 'Allgemeine Einstellungen',
		ru: 'Общие настройки',
		pt: 'Configurações Gerais',
		nl: 'Algemene instellingen',
		fr: 'Réglages généraux',
		it: 'Impostazioni generali',
		es: 'Configuración general',
		pl: 'Ustawienia główne',
		'zh-cn': '常规设置',
	},
	'title-steam': {
		en: 'Steam settings',
		de: 'Steam-Einstellungen',
		ru: 'Настройки Steam',
		pt: 'Configurações do Steam',
		nl: 'Steam-instellingen',
		fr: 'Paramètres Steam',
		it: 'Impostazioni di Steam',
		es: 'Configuración de Steam',
		pl: 'Ustawienia Steam',
		'zh-cn': 'Steam 设置',
	},
};
