/* eslint-disable no-unused-vars */
/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'steam-friends adapter settings': {
		en: 'Adapter settings for steam-friends',
		de: 'Adaptereinstellungen für steam-friends',
		ru: 'Настройки адаптера для steam-friends',
		pt: 'Configurações do adaptador para steam-friends',
		nl: 'Adapterinstellingen voor steam-friends',
		fr: "Paramètres d'adaptateur pour steam-friends",
		it: "Impostazioni dell'adattatore per steam-friends",
		es: 'Ajustes del adaptador para steam-friends',
		pl: 'Ustawienia adaptera dla steam-friends',
		'zh-cn': 'steam-friends的适配器设置',
	},
	'var-apikey': {
		en: 'Your API-Key',
		de: 'Ihr API-Schlüssel',
		ru: 'Ваш API-ключ',
		pt: 'Sua chave de API',
		nl: 'Uw API-sleutel',
		fr: 'Votre clé API',
		it: 'La tua chiave API',
		es: 'Su clave API',
		pl: 'Twój klucz API',
		'zh-cn': '您的 API 密钥',
	},
	'var-refresh': {
		en: 'Update interval (in seconds | please use at least 5 seconds)',
		de: 'Aktualisierungsintervall (in Sekunden | bitte mindestens 5 Sekunden verwenden)',
		ru: 'Интервал обновления (в секундах | используйте не менее 5 секунд)',
		pt: 'Intervalo de atualização (em segundos | use pelo menos 5 segundos)',
		nl: 'Update-interval (in seconden | gebruik a.u.b. minimaal 5 seconden)',
		fr: 'Intervalle de mise à jour (en secondes | veuillez utiliser au moins 5 secondes)',
		it: 'Intervallo di aggiornamento (in secondi | si prega di utilizzare almeno 5 secondi)',
		es: 'Intervalo de actualización (en segundos | utilice al menos 5 segundos)',
		pl: 'Interwał aktualizacji (w sekundach | użyj co najmniej 5 sekund)',
		'zh-cn': '更新间隔（以秒为单位 | 请至少使用 5 秒）',
	},
	'var-steamid': {
		en: 'Your Steam-ID',
		de: 'Ihre Steam-ID',
		ru: 'Ваш Steam-ID',
		pt: 'Seu Steam ID',
		nl: 'Je Steam-ID',
		fr: 'Votre identifiant Steam',
		it: 'Il tuo Steam ID',
		es: 'Tu ID de Steam',
		pl: 'Twój identyfikator Steam',
		'zh-cn': '您的 Steam-ID',
	},
	'tab-main': {
		en: 'Main Settings',
		de: 'Haupteinstellungen',
		ru: 'Основные параметры',
		pt: 'Configurações principais',
		nl: 'Belangrijkste instellingen',
		fr: 'Réglages principaux',
		it: 'Impostazioni principali',
		es: 'Ajustes principales',
		pl: 'Ustawienia główne',
		'zh-cn': '主要设置',
	},
	'tab-visibility': {
		en: 'Change visibility',
		de: 'Sichtbarkeit ändern',
		ru: 'Изменить видимость',
		pt: 'Alterar visibilidade',
		nl: 'Zichtbaarheid wijzigen',
		fr: 'Modifier la visibilité',
		it: 'Cambia visibilità',
		es: 'Cambiar visibilidad',
		pl: 'Zmień widoczność',
		'zh-cn': '更改可见性',
	},
	'text-instruction-start': {
		en: 'To use this adapter, you need to follow 2 steps:\n1. insert your Steam ID and API key in the corresponding fields below. This data will be used to retrieve the data from your friends list.\n2. your Steam friends list must be set to the "Public" setting, otherwise the data cannot be retrieved.',
		de: 'Um diesen Adapter zu verwenden, müssen Sie 2 Schritte befolgen:\n1. Geben Sie Ihre Steam-ID und Ihren API-Schlüssel in die entsprechenden Felder unten ein. Diese Daten werden verwendet, um die Daten aus Ihrer Freundesliste abzurufen.\n2. Ihre Steam-Freundesliste muss auf die Einstellung „Öffentlich“ gesetzt sein, sonst können die Daten nicht abgerufen werden.',
		ru: 'Чтобы использовать этот адаптер, вам необходимо выполнить 2 шага:\n1. введите свой Steam ID и API-ключ в соответствующие поля ниже. Эти данные будут использоваться для получения данных из вашего списка друзей.\n2. ваш список друзей в Steam должен быть установлен на «Общедоступный», иначе данные не могут быть получены.',
		pt: 'Para usar este adaptador, você precisa seguir 2 etapas:\n1. insira seu Steam ID e chave de API nos campos correspondentes abaixo. Esses dados serão usados para recuperar os dados da sua lista de amigos.\n2. sua lista de amigos do Steam deve estar configurada para "Público", caso contrário os dados não poderão ser recuperados.',
		nl: 'Om deze adapter te gebruiken, moet u 2 stappen volgen:\n1. Voer je Steam ID en API-sleutel in in de corresponderende velden hieronder. Deze gegevens worden gebruikt om de gegevens uit uw vriendenlijst op te halen.\n2. je Steam-vriendenlijst moet zijn ingesteld op de instelling "Openbaar", anders kunnen de gegevens niet worden opgehaald.',
		fr: 'Pour utiliser cet adaptateur, vous devez suivre 2 étapes :\n1. insérez votre identifiant Steam et votre clé API dans les champs correspondants ci-dessous. Ces données seront utilisées pour récupérer les données de votre liste d\'amis.\n2. votre liste d\'amis Steam doit être définie sur le paramètre "Public", sinon les données ne peuvent pas être récupérées.',
		it: 'Per utilizzare questo adattatore, devi seguire 2 passaggi:\n1. inserisci il tuo ID Steam e la tua chiave API nei campi corrispondenti sottostanti. Questi dati verranno utilizzati per recuperare i dati dalla tua lista di amici.\n2. la tua lista amici di Steam deve essere impostata sull\'impostazione "Pubblico", altrimenti i dati non possono essere recuperati.',
		es: 'Para usar este adaptador, debe seguir 2 pasos:\n1. inserte su ID de Steam y clave API en los campos correspondientes a continuación. Estos datos se utilizarán para recuperar los datos de su lista de amigos.\n2. su lista de amigos de Steam debe establecerse en la configuración "Pública", de lo contrario, los datos no se pueden recuperar.',
		pl: 'Aby użyć tego adaptera, musisz wykonać 2 kroki:\n1. wprowadź swój identyfikator Steam i klucz API w odpowiednich polach poniżej. Te dane zostaną wykorzystane do pobrania danych z Twojej listy znajomych.\n2. Twoja lista znajomych na Steam musi być ustawiona na „Publiczne”, w przeciwnym razie dane nie będą mogły zostać odzyskane.',
		'zh-cn':
			'要使用此适配器，您需要执行 2 个步骤：\n1. 在下面的相应字段中输入您的 Steam ID 和 API 密钥。此数据将用于从您的朋友列表中检索数据。\n2.您的Steam好友列表必须设置为“公开”设置，否则无法找回数据。',
	},
	'text-instruction-steamid': {
		en: 'To get your Steam ID, the easiest way is to use the following page for it. With this page you can find out the Steam ID you need "steamID64 (Dec)". Example: 76561197960287930',
		de: 'Um Ihre Steam-ID zu erhalten, verwenden Sie am einfachsten die folgende Seite dafür. Mit dieser Seite können Sie die benötigte Steam-ID "steamID64 (Dec)" herausfinden. Beispiel: 76561197960287930',
		ru: 'Чтобы получить свой Steam ID, проще всего использовать следующую страницу. На этой странице вы можете узнать нужный вам Steam ID "steamID64 (Dec)". Пример: 76561197960287930',
		pt: 'Para obter seu Steam ID, a maneira mais fácil é usar a página a seguir. Com esta página você pode descobrir o Steam ID que você precisa "steamID64 (Dec)". Exemplo: 76561197960287930',
		nl: 'Om je Steam-ID te krijgen, is de gemakkelijkste manier om de volgende pagina ervoor te gebruiken. Met deze pagina kun je de Steam ID vinden die je nodig hebt "steamID64 (dec)". Voorbeeld: 76561197960287930',
		fr: 'Pour obtenir votre identifiant Steam, le moyen le plus simple est d\'utiliser la page suivante. Avec cette page, vous pouvez trouver l\'ID Steam dont vous avez besoin "steamID64 (Dec)". Exemple : 76561197960287930',
		it: 'Per ottenere il tuo ID Steam, il modo più semplice è utilizzare la pagina seguente. Con questa pagina puoi scoprire l\'ID Steam di cui hai bisogno "steamID64 (Dec)". Esempio: 76561197960287930',
		es: 'Para obtener su ID de Steam, la forma más fácil es usar la siguiente página. Con esta página puede encontrar la ID de Steam que necesita "steamID64 (diciembre)". Ejemplo: 76561197960287930',
		pl: 'Aby uzyskać swój identyfikator Steam, najprościej jest skorzystać z poniższej strony. Na tej stronie możesz znaleźć identyfikator Steam, którego potrzebujesz „steamID64 (grudzień)”. Przykład: 76561197960287930',
		'zh-cn':
			'要获取您的 Steam ID，最简单的方法是使用以下页面。通过此页面，您可以找到您需要的 Steam ID“steamID64 (Dec)”。示例：76561197960287930',
	},
	'text-instruction-apikey': {
		en: 'To get your API key, the easiest way is to follow the instructions on the following page. Example: M947XROX89UBQ6AOJTOPYJUKAXX6QBTI',
		de: 'Um Ihren API-Schlüssel zu erhalten, folgen Sie am einfachsten den Anweisungen auf der folgenden Seite. Beispiel: M947XROX89UBQ6AOJTOPYJUKAXX6QBTI',
		ru: 'Чтобы получить ключ API, проще всего следовать инструкциям на следующей странице. Пример: M947XROX89UBQ6AOJTOPYJUKAXX6QBTI',
		pt: 'Para obter sua chave de API, a maneira mais fácil é seguir as instruções na página a seguir. Exemplo: M947XROX89UBQ6AOJTOPYJUKAXX6QBTI',
		nl: 'Om uw API-sleutel te verkrijgen, is de eenvoudigste manier om de instructies op de volgende pagina te volgen. Voorbeeld: M947XROX89UBQ6AOJTOPYJUKAXX6QBTI',
		fr: 'Pour obtenir votre clé API, le plus simple est de suivre les instructions de la page suivante. Exemple : M947XROX89UBQ6AOJTOPYJUKAXX6QBTI',
		it: 'Per ottenere la tua chiave API, il modo più semplice è seguire le istruzioni nella pagina seguente. Esempio: M947XROX89UBQ6AOJTOPYJUKAXX6QBTI',
		es: 'Para obtener su clave API, la forma más fácil es seguir las instrucciones en la página siguiente. Ejemplo: M947XROX89UBQ6AOJTOPYJUKAXX6QBTI',
		pl: 'Aby uzyskać klucz API, najłatwiej jest postępować zgodnie z instrukcjami na następnej stronie. Przykład: M947XROX89UBQ6AOJTOPYJUKAXX6QBTI',
		'zh-cn':
			'要获取您的 API 密钥，最简单的方法是按照下一页上的说明进行操作。示例：M947XROX89UBQ6AOJTOPYJUKAXX6QBTI',
	},
	'text-instruction-public': {
		en: 'To make your friends list public on Steam, go to the following page and change the "Friends List" setting to "Public".',
		de: 'Um Ihre Freundesliste auf Steam öffentlich zu machen, gehen Sie zur folgenden Seite und ändern Sie die Einstellung „Freundesliste“ auf „Öffentlich“.',
		ru: 'Чтобы сделать список друзей общедоступным в Steam, перейдите на следующую страницу и измените настройку «Список друзей» на «Общедоступный».',
		pt: 'Para tornar sua lista de amigos pública no Steam, vá para a página a seguir e altere a configuração "Lista de amigos" para "Pública".',
		nl: 'Om je vriendenlijst openbaar te maken op Steam, ga je naar de volgende pagina en verander je de instelling "Vriendenlijst" in "Openbaar".',
		fr: 'Pour rendre votre liste d\'amis publique sur Steam, rendez-vous sur la page suivante et modifiez le paramètre "Liste d\'amis" sur "Public".',
		it: 'Per rendere pubblico il tuo elenco di amici su Steam, vai alla pagina seguente e modifica l\'impostazione "Elenco amici" in "Pubblico".',
		es: 'Para hacer pública su lista de amigos en Steam, vaya a la siguiente página y cambie la configuración de "Lista de amigos" a "Pública".',
		pl: 'Aby upublicznić swoją listę znajomych na Steamie, przejdź na następną stronę i zmień ustawienie „Lista znajomych” na „Publiczna”.',
		'zh-cn':
			'要在 Steam 上公开您的好友列表，请转到以下页面并将“好友列表”设置更改为“公开”。',
	},
	'text-soon': {
		en: 'This feature is coming soon. Please stay patient',
		de: 'Diese Funktion kommt bald. Bitte bleiben Sie geduldig',
		ru: 'Эта функция появится в ближайшее время. Пожалуйста, оставайтесь терпеливыми',
		pt: 'Esta funcionalidade estará disponível em breve. Por favor, seja paciente',
		nl: 'Deze functie komt binnenkort. Blijf alsjeblieft geduldig',
		fr: 'Cette option sera disponible sous peu. Merci de rester patient',
		it: 'Questa funzionalità arriverà presto. Per favore, sii paziente',
		es: 'Esta característica estará disponible en breve. por favor ten paciencia',
		pl: 'Ta funkcja będzie dostępna wkrótce. Prosimy o cierpliwość',
		'zh-cn': '此功能即将推出。请耐心等待',
	},
};
